Modifying contacts

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,7 +39,7 @@ jobs:
               with:
                   token: ${{ secrets.CODECOV_TOKEN }}
                   flags: LWC
-    scratch-org-test:
+    scratch-org-dev:
         runs-on: ubuntu-latest
         needs: format-lint-lwc-tests
         if: github.actor != 'dependabot[bot]'
@@ -56,9 +56,7 @@ jobs:
               shell: bash
               run: >
                   echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
-
                   secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
-
                   if [ $secretFileSize == 1 ]; then
                       echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
                       exit 1;
@@ -67,22 +65,23 @@ jobs:
               run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d
             - name: Authenticate to Scratch Org
               run: >
-                  echo ${{ secrets.SCRATCH_ORG_DEV_SFDX_URL }} >
-                  ./SCRATCH_ORG_DEV_SFDX_URL.txt
-
+                  echo ${{ secrets.SCRATCH_ORG_DEV_SFDX_URL }} > ./SCRATCH_ORG_DEV_SFDX_URL.txt
                   sf org login sfdx-url -f ./SCRATCH_ORG_DEV_SFDX_URL.txt -a Dreamhouse-dev
+            - name: 'Delete dev scratch org'
+              if: always()
+              run: sf org delete scratch -p -o Dreamhouse-dev
+            - name: 'Create scratch org'
+              run: sf org create scratch -f config/project-scratch-def.json -a Dreamhouse-dev -d -y 30
             - name: Set the scratch org as default
               run: sf config set target-org=Dreamhouse-dev
             - name: Push source to scratch org
               run: sf project deploy start --ignore-conflicts
             - name: Assign permissionset to default user
-              run:
-                  sf org assign permset -n dreamhouse || echo "Permission Set already
-                  assigned, continuing..."
+              run: |
+                  sf org assign permset -n dreamhouse && echo "Permission set assigned" || echo "Permission Set already assigned"
             - name: Import sample data
-              run:
-                  sf data tree import -p ./data/sample-data-plan.json || echo "Data already
-                  imported"
+              run: |
+                  sf data tree import -p ./data/sample-data-plan.json && echo "Data successfully imported" || echo "Data already imported or failed"
             - name: Run Apex tests
               run: sf apex test run -c -r human -d ./tests/apex -w 20
             - name: Upload code coverage for Apex to Codecov.io
